# The name of the workflow
name: backend-build

# Triggers for the workflow
on:
  # Manually trigger the workflow
  workflow_dispatch:

  # Automatic trigger when pull request on the main branch
  pull_request:
    branches:
      - main

jobs:
  Lint:
    # Use latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Check out code from repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Install pip and Flake8
      - name: Install pipenv and Flake8
        run: pip install pipenv flake8

      # Cache the dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.OS }}-python-cache-${{ hashFiles('**/backend/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-python-cache-

      # Install the dependencies
      - name: Install dependencies
        run: cd starter/backend && pipenv install

      # Run lint
      - name: Lint
        run: cd starter/backend && pipenv run lint